image: node:22

stages:
  - build

variables:
  ANDROID_SDK_ROOT: "$CI_PROJECT_DIR/android-sdk"
  ANDROID_HOME: "$CI_PROJECT_DIR/android-sdk"

before_script:
  - apt-get update
  - apt-get install -y default-jdk wget unzip

  - mkdir -p $ANDROID_SDK_ROOT/cmdline-tools
  - wget -O tools.zip https://dl.google.com/android/repository/commandlinetools-linux-13114758_latest.zip
  - unzip -q tools.zip -d $ANDROID_SDK_ROOT/cmdline-tools
  - mv $ANDROID_SDK_ROOT/cmdline-tools/cmdline-tools $ANDROID_SDK_ROOT/cmdline-tools/latest

  - export PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/platform-tools:$PATH

  - sdkmanager --version
  - yes | sdkmanager --licenses
  - yes | sdkmanager --sdk_root=$ANDROID_SDK_ROOT "platform-tools" "platforms;android-35" "build-tools;35.0.0"

build_apk:
  stage: build

  script:
    - npm ci
    - npm run build
    - npx cap sync android
    - cd android
    - chmod +x gradlew
    - ./gradlew assembleDebug --no-daemon

  artifacts:
    paths:
      - android/app/build/outputs/apk/debug/app-debug.apk
    expire_in: 1 week